from __future__ import annotations
import html, json
from pathlib import Path
def build(case_dir,output):
 case=Path(case_dir); data=json.loads((case/"case.json").read_text(encoding="utf-8"))
 events=data.get("timeline",[]); evidence=data.get("evidence",[]); findings=data.get("findings",[]); custody=data.get("chain_of_custody",[])
 cards=f"<div class='card'><b>{len(evidence)}</b><span>Evidence</span></div><div class='card'><b>{len(findings)}</b><span>Findings</span></div><div class='card'><b>{len(custody)}</b><span>Custody</span></div><div class='card'><b>{len(events)}</b><span>Events</span></div><div class='card'><b>{html.escape(data.get('status',''))}</b><span>Status</span></div>"
 evidence_rows="".join(f"<tr><td>{html.escape(str(x.get('id','')))}</td><td>{html.escape(str(x.get('name','')))}</td><td>{html.escape(str(x.get('sha256','')))}</td></tr>" for x in evidence)
 finding_rows="".join(f"<tr><td>{html.escape(str(x.get('id','')))}</td><td>{html.escape(str(x.get('severity','')))}</td><td>{html.escape(str(x.get('title','')))}</td></tr>" for x in findings)
 rows="".join(f"<tr><td>{html.escape(str(x.get('time','')))}</td><td>{html.escape(str(x.get('type','')))}</td><td>{html.escape(str(x.get('detail','')))}</td></tr>" for x in events)
 doc=f"""<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>CyberIQ DFIR</title><style>body{{margin:auto;max-width:1100px;padding:32px;background:#070707;color:#eee;font:15px system-ui}}h1{{color:#ff3131}}.grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:14px}}.card{{background:#121212;border:1px solid #302020;padding:22px;border-radius:14px}}.card b,.card span{{display:block}}.card b{{font-size:24px;color:#ff5252}}table{{width:100%;margin-top:25px;border-collapse:collapse}}th,td{{padding:10px;border-bottom:1px solid #292929;text-align:left}}</style></head><body><h1>CyberIQ DFIR Lab</h1><p>Case: {html.escape(data.get('case',''))}</p><div class="grid">{cards}</div><h2>Findings</h2><table><tr><th>ID</th><th>Severity</th><th>Title</th></tr>{finding_rows}</table><h2>Evidence</h2><table><tr><th>ID</th><th>Name</th><th>SHA-256</th></tr>{evidence_rows}</table><h2>Timeline</h2><table><tr><th>Time</th><th>Type</th><th>Detail</th></tr>{rows}</table></body></html>"""
 out=Path(output); out.parent.mkdir(parents=True,exist_ok=True); out.write_text(doc,encoding="utf-8"); return out
